# [Task]: T028, T029, T030, T031, T032, T033, T034
"""
Task service for ActionMind AI business logic.

This module provides the TaskService class which encapsulates all
business logic for task management. It follows the dependency
injection pattern, accepting a StorageInterface for data access.
"""

from datetime import datetime
from typing import List, Optional
from src.models.task import Task, TaskStatus
from src.services.storage import StorageInterface
from src.lib.validation import validate_description


class TaskService:
    """Service layer for task management operations.

    This class provides business logic for creating, retrieving,
    updating, and deleting tasks. It uses dependency injection to
    accept any StorageInterface implementation.

    Attributes:
        _storage: Storage implementation for data persistence

    Example:
        >>> storage = InMemoryStorage()
        >>> service = TaskService(storage)
        >>> task = service.create_task("Buy groceries")
        >>> print(task.id)
        1
    """

    def __init__(self, storage: StorageInterface) -> None:
        """Initialize TaskService with a storage implementation.

        Args:
            storage: StorageInterface implementation for data access

        This uses dependency injection, allowing the storage implementation
        to be swapped without changing business logic (e.g., switching from
        InMemoryStorage to MCP-backed storage in Phase 2).
        """
        self._storage = storage

    def create_task(self, description: str) -> Task:
        """Create a new task with the given description.

        Args:
            description: Human-readable description of the task (1-200 chars)

        Returns:
            Created Task object with auto-generated ID and PENDING status

        Raises:
            ValueError: If description is empty, blank, or too long (>200 chars)

        Business rules:
            - Description is trimmed of leading/trailing whitespace
            - Description must be at least 1 character after trimming
            - Description cannot exceed 200 characters
            - Task is created with PENDING status
            - Task ID is auto-generated by storage
            - Created timestamp is set to current time
        """
        # Validate and normalize description
        normalized_description = validate_description(description)

        # Generate unique ID
        task_id = self._storage.generate_id()

        # Create task with PENDING status
        task = Task(
            id=task_id,
            description=normalized_description,
            status=TaskStatus.PENDING,
            created_at=datetime.now()
        )

        # Store the task
        self._storage.add(task)

        return task

    def get_all_tasks(self) -> List[Task]:
        """Get all tasks from storage.

        Returns:
            List of all tasks in insertion order (oldest first)

            Returns an empty list if no tasks exist.
        """
        return self._storage.get_all()

    def get_task_by_id(self, task_id: int) -> Optional[Task]:
        """Get a specific task by its ID.

        Args:
            task_id: Unique identifier of the task to retrieve

        Returns:
            Task object if found, None if not found

        This is useful for retrieving details of a specific task,
        typically before update or delete operations.
        """
        return self._storage.get_by_id(task_id)

    def complete_task(self, task_id: int) -> bool:
        """Mark a task as completed.

        Args:
            task_id: Unique identifier of the task to complete

        Returns:
            True if task was marked complete
            False if task was not found

        Raises:
            ValueError: If task is already in COMPLETED status

        Business rules:
            - Task must exist in storage
            - Task must not already be completed
            - Task status is changed to COMPLETED
            - Task description and created_at are unchanged
        """
        # Find the task
        task = self._storage.get_by_id(task_id)

        if task is None:
            return False

        # Check if already completed
        if task.status == TaskStatus.COMPLETED:
            raise ValueError("Task is already completed")

        # Update task status
        task.status = TaskStatus.COMPLETED

        # Persist the update
        return self._storage.update(task)

    def delete_task(self, task_id: int) -> bool:
        """Delete a task from storage.

        Args:
            task_id: Unique identifier of the task to delete

        Returns:
            True if task was deleted
            False if task was not found

        Business rules:
            - Task must exist in storage to be deleted
            - Deleted tasks are permanently removed (no undo in Phase 1)
            - Task IDs are NOT reused after deletion
        """
        return self._storage.delete(task_id)

    def get_task_count(self) -> int:
        """Get the total number of tasks.

        Returns:
            Number of tasks in storage

        This is a convenience method for display purposes.
        """
        return len(self._storage.get_all())

    def get_pending_tasks(self) -> List[Task]:
        """Get all tasks with PENDING status.

        Returns:
            List of pending tasks in insertion order

        This is useful for displaying only incomplete tasks.
        """
        return [
            task for task in self._storage.get_all()
            if task.status == TaskStatus.PENDING
        ]

    def get_completed_tasks(self) -> List[Task]:
        """Get all tasks with COMPLETED status.

        Returns:
            List of completed tasks in insertion order

        This is useful for displaying completed work.
        """
        return [
            task for task in self._storage.get_all()
            if task.status == TaskStatus.COMPLETED
        ]
