{{- if .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.backend.name }}-pdb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ActionMindAI.backendLabels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ActionMindAI.name" . }}
      app.kubernetes.io/component: backend
{{- end }}
