apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ActionMindAI.frontendLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "ActionMindAI.name" . }}
    app.kubernetes.io/component: frontend
